import { create } from 'zustand';

type Language = 'en' | 'it';

// English Dictionary
const en = {
    header: {
        map: "Map",
        sipoc: "SIPOC",
        guide: "Guide",
        passport: "Passport",
        projectPlaceholder: "Project Name...",
        subtitle: "Local-First Process Intelligence & RACI Mapping",
    },
    passport: {
        title: "Process Passport (ISO 9001 Governance)",
        description: "Define the identity, boundaries, and control measures of this process.",
        owner: "Process Owner",
        purpose: "Purpose",
        triggers: "Triggers",
        outputs: "Outputs",
        kpis: "KPIs",
        kpisRisks: "KPIs & Risks",
        save: "Save Passport",
        ownerPlaceholder: "e.g. Process Owner Name",
        purposePlaceholder: "e.g. To manage...",
        inputsLabel: "Input / Triggers",
        inputsPlaceholder: "What starts this process? (Inputs, Events)",
        outputsLabel: "Outputs / Deliverables",
        outputsPlaceholder: "What is produced? (Documents, Decisions)",
        kpisLabel: "Key Performance Indicators (KPIs) & Risks",
        kpisPlaceholder: "How is success measured (Lead Time, Quality %)? Key risks?",
    },
    sipoc: {
        suppliers: "Suppliers",
        inputs: "Inputs",
        process: "Process (High Level)",
        outputs: "Outputs",
        customers: "Customers",
        add: "Add Row",
        placeholder: "Enter details...",
        outputsPlaceholder: "What is produced?",
        customersPlaceholder: "Who receives outputs?",
    },
    properties: {
        title: "Properties",
        selectNode: "Select a node or edge to view properties",
        label: "Label",
        edgeLabelPlaceholder: "e.g. Yes, No, > 500$",
        indicators: "Process Indicators",
        risk: "Risk",
        control: "Control",
        kpi: "KPI",
        raci: "RACI Matrix",
        r: "Responsible (R)",
        a: "Accountable (A)",
        c: "Consulted (C)",
        i: "Informed (I)",
    },
    // ... toolbar ...
    tooltips: {
        risk: "Risk Point",
        control: "Control Point",
        kpi: "KPI Measurement",
        missingAccountable: "Missing Accountable",
    },
    sidebar: {
        shapes: "Shapes",
        drag: "Drag to canvas",
        task: "Rectangle (Task)",
        decision: "Decision",
        startEnd: "Oval (Start/End)",
    },
    toolbar: {
        saveJson: "Save JSON",
        loadJson: "Load JSON",
        book: "Process Book",
        excel: "RACI XLSX",
        processMap: "Process Map",
        untitledProcess: "Untitled Process",
        processDefinitionDocument: "Process Definition Document",
    },
    guidance: {
        title: "Quick Tips",
        tip1: "Drag shapes from the sidebar.",
        tip2: "Connect nodes by dragging handles.",
        tip3: "Select a node to edit properties.",
    },
    documentation: {
        title: "MC Synapse Methodological Manual",
        subtitle: "Operational guide to process mapping and Process Intelligence tools.",
        section1: "1. The Process Passport (Governance)",
        section1_desc: "Before drawing any flow, it is essential to define the identity of the process. The Process Passport defines boundaries and responsibilities (ISO 9001 Compliance).",
        section2: "2. Scoping with SIPOC",
        section2_desc: "The SIPOC (Suppliers, Inputs, Process, Outputs, Customers) is a high-level view. Do not enter details here. It serves to understand the context.",
        section3: "3. Flow Mapping (Simplified BPMN)",
        section3_desc: "Draw the operational flow (Flowchart) by dragging elements from the sidebar.",
        section4: "4. RACI Matrix (Responsibility)",
        section4_desc: "For each Task, define who does what. Select a node and use the panel on the right.",
        section5: "5. Control Indicators",
        section5_desc: "Enrich the map by marking critical points. Select a node and toggle flags:",
        section6: "6. Technical Guide & Data Management",
        section6_desc: "This application runs entirely in your browser (Local-First). No data is sent to any server.",
        tech_note1: "Local Storage: If you refresh the page, unsaved changes will be lost. Save your work frequently using the 'Save JSON' button.",
        tech_note2: "Save JSON: Downloads a file (.json) containing your diagram and data. Use 'Load JSON' to restore it later.",
        tech_note3: "RACI XLSX: Downloads an Excel file with the Responsibility Matrix (Role vs Activity).",
        tech_note4: "Process Book: Generates a complete PDF report including the Passport, Map, and RACI Matrix.",
        tech_note5: "Process Map: Exports only the diagram image (PNG/PDF).",
    },
    common: {
        invalidFileStructure: "Invalid project file structure",
        failedToParseFile: "Failed to parse project file",
        exportFailed: "Export failed",
        notDefined: "Not defined",
    },
    roleManager: {
        button: "Manage Roles",
        title: "Manage RACI Roles",
        description: "Add or remove roles available for assignment in the RACI matrix.",
        placeholder: "New Role Name",
    },
    mobileWarning: {
        title: "Desktop Experience Recommended",
        description: "For the best experience, this tool is designed for desktop use, fullscreen. Please open it on your computer.",
        button: "Visit cardux.it",
    },
    feedback: {
        trigger: "Feedback",
        title: "Send Feedback",
        subtitle: "Have suggestions or found a bug?",
        name: "Name",
        namePlaceholder: "Your name",
        email: "Email (Optional)",
        emailPlaceholder: "your@email.com",
        message: "Message",
        messagePlaceholder: "Write your message here...",
        submit: "Send Feedback",
        success: "Feedback sent!",
        error: "Error sending feedback.",
        copyright: "© 2026 cardux.it",
    },
};

// Italian Dictionary
const it: typeof en = {
    header: {
        map: "Mappa",
        sipoc: "SIPOC",
        guide: "Guida",
        passport: "Passaporto",
        projectPlaceholder: "Nome Progetto...",
        subtitle: "Process Intelligence Local-First & Mappatura RACI",
    },
    passport: {
        title: "Passaporto Processo (Governance ISO 9001)",
        description: "Definisci l'identità, i confini e le misure di controllo del processo.",
        owner: "Process Owner",
        purpose: "Scopo",
        triggers: "Trigger",
        outputs: "Output",
        kpis: "KPI",
        kpisRisks: "KPI & Rischi",
        save: "Salva Passaporto",
        ownerPlaceholder: "es. Nome Process Owner",
        purposePlaceholder: "es. Per gestire...",
        inputsLabel: "Input / Trigger",
        inputsPlaceholder: "Cosa avvia il processo? (Input, Eventi)",
        outputsLabel: "Output / Deliverables",
        outputsPlaceholder: "Cosa viene prodotto? (Documenti, Decisioni)",
        kpisLabel: "Key Performance Indicators (KPI) & Rischi",
        kpisPlaceholder: "Come viene misurato il successo? Rischi principali?",
    },
    sipoc: {
        suppliers: "Fornitori",
        inputs: "Input",
        process: "Processo (Macro)",
        outputs: "Output",
        customers: "Clienti",
        add: "Aggiungi Riga",
        placeholder: "Inserisci dettagli...",
        outputsPlaceholder: "Cosa viene prodotto?",
        customersPlaceholder: "Chi riceve gli output?",
    },
    properties: {
        title: "Proprietà",
        selectNode: "Seleziona un nodo o arco per vedere le proprietà",
        label: "Etichetta",
        edgeLabelPlaceholder: "es. Sì, No, > 500€",
        indicators: "Indicatori Processo",
        risk: "Rischio",
        control: "Controllo",
        kpi: "KPI",
        raci: "Matrice RACI",
        r: "Responsible (R)",
        a: "Accountable (A)",
        c: "Consulted (C)",
        i: "Informed (I)",
    },
    tooltips: {
        risk: "Punto di Rischio",
        control: "Punto di Controllo",
        kpi: "Misurazione KPI",
        missingAccountable: "Responsabile Mancante",
    },
    sidebar: {
        shapes: "Forme",
        drag: "Trascina nella mappa",
        task: "Rettangolo (Attività)",
        decision: "Decisione",
        startEnd: "Ovale (Inizio/Fine)",
    },
    toolbar: {
        saveJson: "Salva JSON",
        loadJson: "Carica JSON",
        book: "Process Book",
        excel: "RACI XLSX",
        processMap: "Mappa del Processo",
        untitledProcess: "Processo Senza Nome",
        processDefinitionDocument: "Documento di Definizione Processo",
    },
    guidance: {
        title: "Suggerimenti",
        tip1: "Trascina le forme dalla barra laterale.",
        tip2: "Collega i nodi trascinando le maniglie.",
        tip3: "Seleziona un nodo per modificare le proprietà.",
    },
    documentation: {
        title: "Manuale Metodologico MC Synapse",
        subtitle: "Guida operativa alla mappatura dei processi e all'utilizzo degli strumenti di Process Intelligence.",
        section1: "1. Il Passaporto del Processo (Governance)",
        section1_desc: "Prima di disegnare qualsiasi flusso, è fondamentale definire la carta d'identità del processo. Il Process Passport serve a stabilire i confini e le responsabilità (Compliance ISO 9001).",
        section2: "2. Lo Scoping con il SIPOC",
        section2_desc: "Il SIPOC (Suppliers, Inputs, Process, Outputs, Customers) è una vista 'dall'alto' (High-Level). Non entrare nei dettagli qui. Serve a capire il contesto.",
        section3: "3. Mappatura del Flusso (BPMN Semplificato)",
        section3_desc: "Disegna il flusso operativo (Flowchart) trascinando gli elementi dalla barra laterale.",
        section4: "4. Matrice RACI (Responsabilità)",
        section4_desc: "Per ogni Task, devi definire chi fa cosa. Seleziona un nodo e usa il pannello a destra.",
        section5: "5. Indicatori di Controllo",
        section5_desc: "Arricchisci la mappa segnando i punti critici. Seleziona un nodo e attiva i flag:",
        section6: "6. Guida Tecnica & Gestione Dati",
        section6_desc: "Questa applicazione gira interamente nel tuo browser (Local-First). Nessun dato viene inviato a server esterni.",
        tech_note1: "Salvataggio Locale: Se ricarichi la pagina, i dati non salvati andranno persi. Salva frequentemente con il tasto 'Salva JSON'.",
        tech_note2: "Salva JSON: Scarica un file (.json) con il diagramma e tutti i dati. Usa 'Carica JSON' per ripristinarlo.",
        tech_note3: "RACI XLSX: Scarica un file Excel con la Matrice delle Responsabilità (Ruoli vs Attività).",
        tech_note4: "Process Book: Genera un report PDF completo che include Passaporto, Mappa e Matrice RACI.",
        tech_note5: "Mappa del Processo: Esporta solo l'immagine del diagramma (PNG/PDF).",
    },
    common: {
        invalidFileStructure: "Struttura file non valida",
        failedToParseFile: "Impossibile leggere il file",
        exportFailed: "Esportazione fallita",
        notDefined: "Non definito",
    },
    roleManager: {
        button: "Gestisci Ruoli",
        title: "Gestisci Ruoli RACI",
        description: "Aggiungi o rimuovi ruoli disponibili per l'assegnazione nella matrice RACI.",
        placeholder: "Nome Nuovo Ruolo",
    },
    mobileWarning: {
        title: "Esperienza Ottimizzata per Desktop",
        description: "Per un'esperienza ottimale, questo strumento è progettato per l'uso su desktop a tutto schermo. Ti invitiamo ad aprirlo dal tuo computer.",
        button: "Visita cardux.it",
    },
    feedback: {
        trigger: "Feedback",
        title: "Invia Feedback",
        subtitle: "Hai suggerimenti o hai trovato un bug?",
        name: "Nome",
        namePlaceholder: "Il tuo nome",
        email: "Email (Facoltativo)",
        emailPlaceholder: "tua@email.com",
        message: "Messaggio",
        messagePlaceholder: "Scrivi qui il tuo messaggio...",
        submit: "Invia Feedback",
        success: "Feedback inviato!",
        error: "Errore nell'invio.",
        copyright: "© 2026 cardux.it",
    },
};

interface LanguageState {
    language: Language;
    t: typeof en;
    setLanguage: (lang: Language) => void;
}

export const useLanguageStore = create<LanguageState>((set) => ({
    language: 'it', // Defaulting to Italian
    t: it,
    setLanguage: (lang) => set({
        language: lang,
        t: lang === 'en' ? en : it
    }),
}));
